"""
Shadow Vault — Persistent storage for tools, scripts, configs, knowledge, and reusable components.

The Vault is Shadow's growing toolbox. Every tool built by the Bot Factory gets registered
here, along with any scripts, configurations, or knowledge modules that Shadow creates or
discovers. The Vault persists across sessions as JSON files on disk.

Categories:
  - tools:       Executable scripts generated by the Bot Factory
  - scripts:     Shell/Python helper scripts
  - configs:     Configuration templates and saved settings
  - knowledge:   Extracted knowledge documents (from the Learning System)
  - components:  Reusable code components and modules
  - snippets:    Code snippets and patterns
"""
import os
import json
import time
import shutil
from pathlib import Path
from typing import Dict, Any, List, Optional

from logging.logger import ShadowLogger

log = ShadowLogger.get("shadow.vault")

VAULT_DIR = Path(__file__).parent / "data"


class Vault:
    """Shadow's persistent toolbox — stores tools, scripts, configs, knowledge, and components."""

    CATEGORIES = {"tools", "scripts", "configs", "knowledge", "components", "snippets"}

    def __init__(self, vault_dir: Optional[str] = None):
        self.vault_dir = Path(vault_dir) if vault_dir else VAULT_DIR
        self.vault_dir.mkdir(parents=True, exist_ok=True)
        for cat in self.CATEGORIES:
            (self.vault_dir / cat).mkdir(parents=True, exist_ok=True)
        self._index = self._load_index()
        log.info(f"Vault initialized at {self.vault_dir} ({self._index['total_items']} items)")

    def _load_index(self) -> dict:
        index_path = self.vault_dir / "index.json"
        if index_path.exists():
            try:
                with open(index_path) as f:
                    return json.load(f)
            except Exception:
                pass
        return {"items": {}, "total_items": 0}

    def _save_index(self):
        index_path = self.vault_dir / "index.json"
        with open(index_path, "w") as f:
            json.dump(self._index, f, indent=2)

    def store(self, category: str, name: str, content: str, metadata: Optional[dict] = None) -> dict:
        """Store an item in the Vault."""
        if category not in self.CATEGORIES:
            return {"success": False, "error": f"Unknown category: {category}"}

        safe_name = name.replace(" ", "_").replace("/", "_")
        file_path = self.vault_dir / category / safe_name
        file_path.parent.mkdir(parents=True, exist_ok=True)

        with open(file_path, "w") as f:
            f.write(content)

        item_id = f"{category}/{safe_name}"
        entry = {
            "id": item_id,
            "category": category,
            "name": name,
            "file": str(file_path),
            "metadata": metadata or {},
            "created": time.time(),
            "access_count": 0,
        }
        self._index["items"][item_id] = entry
        self._index["total_items"] = len(self._index["items"])
        self._save_index()

        log.info(f"Stored {item_id} in Vault")
        return {"success": True, "id": item_id, "path": str(file_path)}

    def retrieve(self, item_id: str) -> Optional[str]:
        """Retrieve item content by ID (e.g. 'tools/square_root')."""
        entry = self._index["items"].get(item_id)
        if not entry:
            return None
        file_path = Path(entry["file"])
        if not file_path.exists():
            return None
        entry["access_count"] += 1
        self._save_index()
        return file_path.read_text()

    def list_items(self, category: Optional[str] = None) -> List[dict]:
        """List all items, optionally filtered by category."""
        items = list(self._index["items"].values())
        if category:
            items = [i for i in items if i["category"] == category]
        return sorted(items, key=lambda x: x.get("created", 0), reverse=True)

    def delete(self, item_id: str) -> dict:
        """Remove an item from the Vault."""
        entry = self._index["items"].pop(item_id, None)
        if not entry:
            return {"success": False, "error": "Item not found"}
        file_path = Path(entry["file"])
        if file_path.exists():
            file_path.unlink()
        self._index["total_items"] = len(self._index["items"])
        self._save_index()
        log.info(f"Deleted {item_id} from Vault")
        return {"success": True}

    def search(self, query: str) -> List[dict]:
        """Search items by name or metadata."""
        query_lower = query.lower()
        results = []
        for entry in self._index["items"].values():
            name_match = query_lower in entry["name"].lower()
            meta_str = json.dumps(entry.get("metadata", {})).lower()
            meta_match = query_lower in meta_str
            if name_match or meta_match:
                results.append(entry)
        return sorted(results, key=lambda x: x.get("created", 0), reverse=True)

    def get_stats(self) -> dict:
        """Return summary statistics about the Vault."""
        by_category = {}
        for cat in self.CATEGORIES:
            by_category[cat] = sum(
                1 for e in self._index["items"].values() if e["category"] == cat
            )
        return {
            "total_items": self._index["total_items"],
            "by_category": by_category,
            "vault_dir": str(self.vault_dir),
        }
